{"level":"error","message":"Error while fetching the todos Database failure","service":"user-service","stack":"Error: Database failure\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:43:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:11:05.856Z"}
{"level":"error","message":"Error while fetching the todos Database failure","service":"user-service","stack":"Error: Database failure\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:43:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:14:49.274Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:43:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:16:30.501Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:45:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T13:28:41.199Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T14:58:43.954Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T14:59:21.434Z"}
{"level":"error","message":"Error while fetching the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:48:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T15:06:31.765Z"}
{"level":"error","message":"Error while adding  the todos something went wrong...","service":"user-service","stack":"Error: something went wrong...\n    at Object.<anonymous> (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\__tests__\\controllers\\todoControllers.test.js:76:40)\n    at Promise.then.completed (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:298:28)\n    at new Promise (<anonymous>)\n    at callAsyncCircusFn (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\utils.js:231:10)\n    at _callCircusTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:316:40)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at _runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:252:3)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:126:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at _runTestsForDescribeBlock (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:121:9)\n    at run (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\run.js:71:3)\n    at runAndTransformResultsToJestFormat (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapterInit.js:122:21)\n    at jestAdapter (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:79:19)\n    at runTestInternal (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at runTest (D:\\devops_practise\\Devops\\todo-app\\todo-backend\\node_modules\\jest-runner\\build\\runTest.js:444:34)","timestamp":"2025-04-27T15:06:31.795Z"}
